import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { ResumeProvider } from "@/context/resume";
import { ClerkProvider } from "@clerk/nextjs";
import { saveResumeToDb } from "@/lib/actions";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "AI Resume Builder",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ClerkProvider>
					<ResumeProvider>
						<Navbar />
						<main className="mx-auto mt-20 max-w-7xl">{children}</main>
						<Toaster />
					</ResumeProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
